// import './modules/h.spec'
// import './modules/createElement.spec'
// import './modules/diff.spec'
// import './modules/render.spec'
// import './modules/refs.spec'
// import './modules/keys.spec'
// import './modules/svg.spec'
import './modules/component.spec'
// import './modules/context.spec'
// import './modules/lifecycle.spec'
