import './util/ie8'
// import './modules/util.spec'
import './modules/h.spec'
import './modules/createElement.spec'
import './modules/diff.spec'
import './modules/vtypes.spec'
import './modules/render.spec'
import './modules/refs.spec'
import './modules/keys.spec'
import './modules/svg.spec'
import './modules/event.spec'
import './modules/component.spec'
import './modules/context.spec'
import './modules/lifecycle.spec'
import './modules/cloneElement.spec'
import './modules/patch.spec'
import './modules/hook.spec'
