import './modules/h.spec'
import './modules/createElement.spec'
import './modules/diff.spec'
import './modules/component.spec'
import './modules/context.spec'
import './modules/lifecycle.spec'
import './modules/render.spec'
